# Behavioural Data Notes

## Training

This experiment uses a block-based design and shows participants stimuli of real motion.

In each block, stimuli moving in one direction (left, right, forward, backward) is presented. Within a block, the speed of movement varies across trials, and participants are asked to press a button when the speed increases from one trial to the next.

Note that running the experiment script (`trainIMD` or variants) creates only 1 run! So, for each participant, the script was run 8 times, and there were 8 log files per participant.

The presented conditions, number of blocks, velocity parameters, run duration etc. match with what is written on the script.

## Test

This experiment uses a block-based design and shows participants stimuli of implied motion.

In each block, stimuli moving in one direction (left, right, forward, backward) is presented. They performed a 1-back task to maintain
attention on the images and pressed a key when the same image (matching both fore- and background) was presented the second time in a row, which occurred randomly once per block.

Note that running the experiment script (`testIMD` or variants) creates only 1 run! So, for each participant, the script was run 8 times, and there were 8 log files per participant.

The presented conditions, number of blocks, velocity parameters, run duration etc. match with what is written on the script.

## Stimulus Presentation and Scanning Parameters

Everything in this table is obtained from the matlab scripts only (except the correct TR). Some of these are to be cross-checked with the imaging data.

| parameter | value |
| ----------| ------|
| width| 1280px|
| height| 1024 px|
| response button | 4$ (pressed using right index finger) |
| dummy TRs | 8 (plus there is an additional manual pulse from the researcher at the beginning)|
| TR | 1.2 seconds (for the first three participants it is .6 seconds), but these data are discarded|
| refresh rate | 60 Hz |
| background | grey [123,123,123] |
| trigger button | w |
| zoom in condition | 1 |
| zoom out condition | 2 |
| right movement condition | 3 |
| left movement condition | 4 |
| speeds of movement | [4, 8, 12, 16, 20, 24 , 28, 32] |
| image per block | 8 |
| image presentation duration | 1.5 seconds |
| inter block interval | 8 seconds |
| total block no per run | 16 |
| total number of runs | 8 |
| total functional images per run | Gizem reports 509 (including 8 dummies). However, this is based on the `TR` she manually enters, which is incorrect for the analysed data. Number of functional images is therefore half the reported number, which is 254 |
| time of run (roughly) | 305 seconds

## Recorded Data File Structure

Files are recorded as `.mat` files with the following name structure:

`e01s{participant no}_{block no}_{block type}_{date}.mat`

where block numbers go from 1 to 16 (mixed across block types) and block types are Train (real motion) or Test (implied motion).

On the first level of the struct, field contain a lot of meta-data that is either written above or found in the scripts. An important field is `logs` which contains different info for the train and test blocks. Here are the shared ones:

- blockSeq: Numbers from 1 to 4, each of which correspond to a condition (see above).
- blockOnsets: Onset time of the block
- timeStart: start of the run (after dummies)
- fmri: start of the run (with dummies)

For Train, there are the additional following fields:

- speedtask: 136 by 3 array. Each row is a trial. First column specifies the block (1 to 17). Second column specifies the velocity of stimulus. Third column specifies the onset of the trial.
- tKeyPresses: Timing of key presses
- blockIntTE: 17 by 2 array. Each row is a block. First column specifies the block type (1 to 4). Second column specifies the duration between blocks.
- blockOffsets: Offset time of the block

For Test, there are the additional following fields:

- ifi: flip interval of the monitor
- blockImgSeq: 136 by 2 array. First column specifies the block type (1 to 4). Second column specifies the image identity no in a given trial.
- tBackMatches: An array of varying length (min 17) which specifies the timing of repeating stimuli. Note that this does not match the description of what is written in the manuscript, which is that images repeat only once per block.
- taskKeyPresses: Response of participants when they thought they saw matching images
- blockOffsets: Offset time of the block PLUS the inter block interval
- bintOnset: Offset time of the block (excluding the interblock interval)


